server:
  port: 8095

spring:
  profiles:
    active: default
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  main:
    banner-mode: off
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test_client_info
    username: postgres
    password: postgres
    platform: postgres
    continue-on-error: true
    configuration:
      maximum-pool-size: 3
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop
      #ddl-auto: update
      #ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
values:
  url:
    client:
      controller: client
      new: new
      by_id: by_id
      all: all
    contact:
      controller: contact
      new: new
      by_client_id: by_client_id
      by_type_and_client_id: by_type_and_client_id



